deliverkindle/books/urls.py
#encoding:utf-8

#from settings import *
from django.conf.urls import *


urlpatterns = patterns('deliverkindle.books',
    (r'^$','views.books_list'),#列表页
    (r'^p(\d{1,10})/$','views.books_list'),#列表翻页
    # (r'^category/(\d+)/$','views.category_book_list'),#列表翻页
    # (r'^category/(\d+)/p(\d{1,10})/$','views.category_book_list'),#列表翻页
    (r'^(\d+)/$','views.books_detail'),#详细页面
    (r'^reader/(\d+)/(.*)$','views.open_book'),#详细页面
    (r'^search/$','views.search'),
    (r'^search/p(\d{1,10})/(.*)$','views.search'),
    (r'^mark/$','views.favorite_mark'),
    (r'^download/(\d{1,10})/(.*)$', 'views.download'),

)

deliverkindle/home/urls.py
#encoding:utf-8

from django.conf.urls import *

urlpatterns = patterns('deliverkindle.home',
    (r'^$','views.bookshelf'),
    (r'^p(\d{1,10})/$','views.bookshelf'),
    (r'^(\d{1,10})/$','profile.index'),
    (r'^(\d{1,10})/p(\d{1,10})/$','profile.index'),
    (r'^(\d{1,10})/follow/$','relation.follow'),
    (r'^(\d{1,10})/follows/$','relation.follows'),
    (r'^(\d{1,10})/fans/$','relation.fans'),

    (r'^bookshelf/$','views.bookshelf'),
    (r'^bookshelf/p(\d{1,10})/$','views.bookshelf'),

    (r'^(\d{1,10})/topic/$','views.topic'),
    (r'^(\d{1,10})/topic/p(\d{1,10})/$','views.topic'),

    (r'^download/','views.download'),
    (r'^download/p(\d{1,10})/$','views.download'),

    (r'^edit/$','profile.edit'),
    (r'^delete/$','profile.delete'),
    (r'^password/$','profile.password'),
    (r'^photo/$','profile.photo'),
    (r'^link/$','profile.link'),
    (r'^city/$','city.index'),
    (r'^members/$','views.members'),
    (r'^members/p(\d{1,10})/$','views.members'),
)

deliverkindle/main/urls.py
#encoding:utf-8


from django.conf.urls import *

urlpatterns = patterns('deliverkindle.main',
    (r'^usernav/$','views.usernav'),
)

deliverkindle/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls import *
from django.conf import settings
from django.conf.urls.static import static
#from deliverkindle.main.feed import BookFeed
from django.contrib import admin

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

admin.autodiscover()
urlpatterns = patterns('',
    (r'^$','deliverkindle.main.views.index'),
    (r'^category/$','deliverkindle.books.views.category_list'),
    (r'^category/(\d+)/$','deliverkindle.books.views.category_book_list'),
    (r'^category/(\d+)/p(\d{1,10})/$','deliverkindle.books.views.category_book_list'),
	(r'^books/',include('deliverkindle.books.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    #(r'^favorites/', include('deliverkindle.favorites.urls')),
    (r'^main/',include('deliverkindle.main.urls')),
    (r'^accounts/',include('deliverkindle.accounts.urls')),
    (r'^home/',include('deliverkindle.home.urls')),
    (r'^topic/',include('deliverkindle.topic.urls')),
    (r'^about/','deliverkindle.main.views.about'),
    (r'^disclaimer/','deliverkindle.main.views.disclaimer'),
    (r'^contact/','deliverkindle.main.views.contact'),
    (r'^partner/','deliverkindle.main.views.partner'),
    (r'^subscribe/$','deliverkindle.main.views.subscribe'),
    #(r'^feeds/$',BookFeed()),
    (r'^admin/', admin.site.urls),
	#(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.ROOT_PATH}),
	
	#(r'^(?P<path>.*)$','django.views.static.serve',{'document_root':settings.ROOT_PATH}),

    # Examples:
    # url(r'^$', 'deliverkindle.views.home', name='home'),
    # url(r'^deliverkindle/', include('deliverkindle.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

deliverkindle/accounts/models.py
#encoding:utf-8
"""
pythoner.net
Copyright (C) 2013  PYTHONER.ORG

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.contrib.auth.models import User
from django.db import models
from django.core.mail import send_mail
from django.db.models.signals import post_save

class UserProfile(models.Model):
    """
    用户资料 pythoner_net
    """
    user = models.ForeignKey(User,unique=True)
    screen_name = models.CharField('昵称',max_length=10,blank=False,null=False,help_text='长度为1~10个字符')
    score = models.PositiveIntegerField('积分',max_length=5,default=0)
    deleted = models.BooleanField('删除',default=False)
    
    photo = models.ImageField('头像',upload_to='user',blank=True)
    city = models.CharField('城市',max_length=15,default='北京')
    status = models.CharField('签名',max_length=150,blank=True,help_text='设置你的签名，最大长度为150字符')
    introduction = models.CharField('介绍',max_length=200,blank=True,help_text='个人介绍最大长度为200字符')
    #signup_from = models.CharField('signup from',max_length=30,default='pythoner')

    def __unicode__(self):
        return self.screen_name

class Link(models.Model):
    user = models.ForeignKey(User)
    type= models.CharField('类型',max_length=10)
    name = models.CharField('链接名称',max_length=20)
    url = models.URLField('链接')

    def __unicode__(self):
        return self.link

deliverkindle/accounts/forms.py
#encoding:utf-8
"""
pythoner.net
Copyright (C) 2013  PYTHONER.ORG

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django import forms
from models import UserProfile

class RegisterForm(forms.Form):
    """
    账号注册表单
    """
    username = forms.EmailField(label='信箱',help_text='填写正确的Email以便激活你的账户')
    screen_name = forms.CharField(label='昵称',required=True,max_length=20,min_length=3,help_text='长度在3~30个字符以内')
    password = forms.CharField(label='密码',required=True,max_length=20,min_length=6,help_text='长度在6~30个字符以内',widget=forms.PasswordInput())

class LoginForm(forms.Form):
    username = forms.EmailField(label='信箱',required=True,max_length=30,min_length=3)
    password = forms.CharField(label='密码',required=True,max_length=128,min_length=6,
                               widget=forms.PasswordInput(),help_text='')

deliverkindle/books/forms.py
#encoding:utf-8

from django import forms

class SearchForm(forms.Form):
    q = forms.CharField(label='',required=False,max_length=50,min_length=1)

deliverkindle/home/forms.py
#encoding:utf-8
"""
pythoner.net
Copyright (C) 2013  PYTHONER.ORG

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django import forms
from deliverkindle.accounts.models import UserProfile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        widgets = {'introduction':forms.Textarea()}
        exclude = ('score','deleted','photo','user','city')

class PhotoForm(forms.Form):
    photo = forms.ImageField(label='',max_length=1024)

deliverkindle/accounts/views.py
#encoding:utf-8
"""
pythoner.net
Copyright (C) 2013  PYTHONER.ORG

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.template import RequestContext
from django.shortcuts import render_to_response as render
from django.contrib.auth import authenticate,login as auth_login,logout as auth_logout
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.models import User
from django.template import loader
from forms import *
from models import UserProfile
from deliverkindle.settings import DOMAIN
from deliverkindle.accounts.signals import new_user_register
from deliverkindle.main.email.views import send_email
import hashlib
import time

TURN_OFF = False
#DOMAIN = 'http://www.deliverkindle.com'
@csrf_protect
def register(request):
    """
    新用户注册
    """

    if request.method == 'GET':
        if TURN_OFF:
            return render('account_register_off.html',locals())
        else:
            form = RegisterForm()
            return render('account_register.html',locals(),context_instance=RequestContext(request,{'user':request.user}))

    return _register(request)

def _register(request):
    """
    用户注册
    """
    form = RegisterForm(request.POST)
    zen  = request.POST.get('zen')

    if not zen:
        messages.error(request,'对不起，你没有同意《The Zen Of Python》,暂时不能加入')
        return render('account_register.html',locals(),context_instance=RequestContext(request,{'user':request.user}))

    if form.is_valid():
        data = form.clean()
    else:
        print "aaaa"
        return render('account_register.html',locals(),context_instance=RequestContext(request,{'user':request.user}))

    # 检查email是否存在
    try:
        user = User.objects.get(username=data['username'])
    except User.DoesNotExist:
        pass
    else:
        messages.error(request,'email已经注册过，请换一个')
        print "11"
        return render('account_register.html',locals(),context_instance=RequestContext(request,{'user':request.user}))

    # 创建新用户
    new_user = User.objects.create_user(username=data['username'],email=data['username'],
                                        password=data['password'])
    new_user.is_active = False
    new_user.save()
    new_profile = UserProfile(user=new_user,screen_name=data['screen_name'])

    try:
        new_profile.save()
        return HttpResponseRedirect('/accounts/active/%d/not_active/' %new_user.id)
    except Exception,e:
        messages.error(request,'服务器出现错误：%s' %e)

    print "messages"

    return render('account_register.html',locals(),context_instance=RequestContext(request,{'user':request.user}))

@csrf_protect
def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))

    if request.method == 'GET':

        referer  = request.META.get('HTTP_REFERER','/')
        if not 'accounts' in str(referer) :
            request.session['referer'] = referer
        else :
            request.session['referer'] = '/'
        form = LoginForm()
        return render('account_login.html',locals(),context_instance=RequestContext(request,{'user':request.user}))
    

    form = LoginForm(request.POST)
    if form.is_valid():
        data = form.clean()

        # 检查email是否存在
        try:
            user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            messages.error(request,"这个email还没注册过，<a href=\"/accounts/register/\">果断注册</a>")
            return render('account_login.html',locals(),context_instance=RequestContext(request,{'user':request.user}))

        user = authenticate(username=data['username'],password=data['password'])
        if user is not None:
            if user.is_active:
                auth_login(request,user)
                next = request.GET.get('next',False) or request.session['referer'] # 下页地址
                return HttpResponseRedirect(next)
            else:
                return HttpResponseRedirect('/accounts/active/%d/%s/' %(user.id,'not_active'))
        else:
            messages.error(request,'密码错误！')

    return render('account_login.html',locals(),context_instance=RequestContext(request,{'user':request.user}))

def logout(request):
    """
    退出登录
    """
    auth_logout(request)
    referer  = request.META.get('HTTP_REFERER','/')
    request.session['access_token'] = ''
    request.session['request_token'] = ''
    return HttpResponseRedirect(referer)
@csrf_protect 
def active(request,u_id,active_code):
    """
    用户账号激活处理
    """
    # XXX

    try:
        u_id = int(u_id)
        user = User.objects.get(id=u_id)
    except (User.DoesNotExist,ValueError):
        return HttpResponseRedirect('/')

    # 已经激活过
    if user.is_active:
        messages.success(request,'账号已经激活，请直接登录')
        return HttpResponseRedirect('/accounts/login/')

    # 验证激活码是否正确
    elif active_code == _get_active_code(user.email):
        user.is_active = True
        user.save()
        messages.success(request,'恭喜，账号激活成功！马上登录，体验一下吧。')

        # 发送信号
        new_user_register.send(
            sender=user.get_profile().__class__,
            profile = user.get_profile()
        )
        return HttpResponseRedirect('/accounts/login/')
    elif active_code == 'not_active':

        active_url = '%s/accounts/active/%d/%s/' %(DOMAIN,user.id,_get_active_code(user.username))
        subject = '梦想读书社区-账号激活邮件'
        body = loader.render_to_string('account_active.email.html',{'user':user,'active_url':active_url})
        from_email = 'sgqjpw@gmail.com'
        to = [user.username]
        # 开启发送激活邮件线程
        send_email(subject,body,from_email,to)

        #  根据邮件地址找到信箱登录地址
        email_domains = {
            'qq.com':'mail.qq.com',
            'foxmail.com':'mail.qq.com',
            'gmail.com':'www.gmail.com',
            '126.com':'www.126.com',
            '163.com':'www.163.com',
            '189.cn':'www.189.cn',
            '263.net':'www.263.net',
            'yeah.net':'www.yeah.net',
            'sohu.com':'mail.sohu.com',
            'tom.com':'mail.tom.com',
            'hotmail.com':'www.hotmail.com',
            'yahoo.com.cn':'mail.cn.yahoo.com',
            'yahoo.cn':'mail.cn.yahoo.com',
            '21cn.com':'mail.21cn.com',
        }

        for key,value in email_domains.items():
            print user.username.count(key)
            if user.username.count(key) >= 1:
                email_domain = value
                break

        return render('account_active.html',locals(),context_instance=RequestContext(request,{'user':request.user}))
    else:
        raise Http404()

def _get_active_code(email):
    """
    计算激活码
    """
    #TODO:代码开源了之后用户可以根据这里计算出激活码，为防止破解
    #     可随机生成激活码后存入数据库。有时间了优化这里
    date_str = time.strftime('%Y-%m-%d',time.localtime()) # 当天内有效
    m = hashlib.md5(str(email)+'pythoner.net'+'axweraf9092443lklnfd0f89dmrej'+date_str)
    return m.hexdigest()

deliverkindle/favorites/views.py
# -*- coding: utf-8 -*-
#Copyright (C) 2013  David

#Python imports
from datetime import datetime
import logging

#Django imports
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseNotAllowed
from django.contrib.auth.decorators import login_required
from models import MyFavorites
logger = logging.getLogger(__name__)

@login_required
def collection(request,book_id):
    user_id = request.user.id
    try:
        # obj, created = MyFavorites.objects.get_or_create(user_id=user_id, book_id=book_id)
        # msg = '{"is_exists":false}' if created else '{"is_exists":true}'
        try:
            MyFavorites.objects.get(user_id=user_id, book_id=book_id)
            return HttpResponse('{"is_exists":true}', mimetype="text/plain")
        except MyFavorites.DoesNotExist:
            MyFavorites.objects.create(user_id=user_id, book_id=book_id)
            return HttpResponse('{"is_exists":false}', mimetype="text/plain")
    except Exception as e:
        print e
        error_msg = 'Bad Request or Handling Exceptions'
        return HttpResponseBadRequest(error_msg, mimetype="text/plain")

def delete(request,book_id):
    user_id = request.user.id
    try:
    	MyFavorites.objects.get(book_id=book_id,user_id=user_id).delete()
    	return HttpResponse('', mimetype="text/plain")
    except:
        error_msg = 'Bad Request or Handling Exceptions'
        return HttpResponseBadRequest(error_msg, mimetype="text/plain")

deliverkindle/templates/comments/400-debug.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>Comment post not allowed (400)</title>
  <meta name="robots" content="NONE,NOARCHIVE" />
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Comment post not allowed <span>(400)</span></h1>
    <table class="meta">
      <tr>
        <th>Why:</th>
        <td>{{ why }}</td>
      </tr>
    </table>
  </div>
  <div id="info">
    <p>
    The comment you tried to post to this view wasn't saved because something
    tampered with the security information in the comment form. The message
    above should explain the problem, or you can check the <a
    href="http://docs.djangoproject.com/en/dev/ref/contrib/comments/">comment
    documentation</a> for more help.
    </p>
  </div>

  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 400 error page.
    </p>
  </div>
</body>
</html>

deliverkindle/templates/comments/approve.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Approve a comment" %}{% endblock %}

{% block content %}
  <h1>{% trans "Really make this comment public?" %}</h1>
  <blockquote>{{ comment|linebreaks }}</blockquote>
  <form action="." method="post">{% csrf_token %}
    {% if next %}<input type="hidden" name="next" value="{{ next }}" id="next" />{% endif %}
    <p class="submit">
      <input type="submit" name="submit" value="{% trans "Approve" %}" /> or <a href="{{ comment.get_absolute_url }}">cancel</a>
    </p>
  </form>
{% endblock %}

deliverkindle/templates/comments/approved.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for approving" %}.{% endblock %}

{% block content %}
  <h1>{% trans "Thanks for taking the time to improve the quality of discussion on our site" %}.</h1>
{% endblock %}

deliverkindle/templates/comments/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>{% block title %}{% endblock %}</title>
<style type="text/css">
#content{
    width:920px;
    margin:0 auto;
    border-bottom:4px solid #3975CE;
    border-top:4px solid #3975CE;
}
</style>
</head>
<body>
  <div id="content">
  {% block content %}{% endblock %}
  </div>
</body>
</html>

deliverkindle/templates/comments/delete.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Remove a comment" %}{% endblock %}

{% block content %}
<h1>{% trans "Really remove this comment?" %}</h1>
  <blockquote>{{ comment|linebreaks }}</blockquote>
  <form action="." method="post">{% csrf_token %}
    {% if next %}<input type="hidden" name="next" value="{{ next }}" id="next" />{% endif %}
    <p class="submit">
    <input type="submit" name="submit" value="{% trans "Remove" %}" /> or <a href="{{ comment.get_absolute_url }}">cancel</a>
    </p>
  </form>
{% endblock %}

deliverkindle/templates/comments/deleted.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for removing" %}.{% endblock %}

{% block content %}
  <h1>{% trans "Thanks for taking the time to improve the quality of discussion on our site" %}.</h1>
{% endblock %}

deliverkindle/templates/comments/flag.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Flag this comment" %}{% endblock %}

{% block content %}
<h1>{% trans "Really flag this comment?" %}</h1>
  <blockquote>{{ comment|linebreaks }}</blockquote>
  <form action="." method="post">{% csrf_token %}
    {% if next %}<input type="hidden" name="next" value="{{ next }}" id="next" />{% endif %}
    <p class="submit">
    <input type="submit" name="submit" value="{% trans "Flag" %}" /> or <a href="{{ comment.get_absolute_url }}">cancel</a>
    </p>
  </form>
{% endblock %}

deliverkindle/templates/comments/flagged.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for flagging" %}.{% endblock %}

{% block content %}
  <h1>{% trans "Thanks for taking the time to improve the quality of discussion on our site" %}.</h1>
{% endblock %}

deliverkindle/templates/comments/form.html
<style>
#id_name,#id_email,#id_url{width:250px;}
div.please-login{border:1px solid #ccc;padding:2px 10px;text-align:right;background:#ffc;}
form.comment #id_comment{width:640px;}
form.comment label{font-weight:800;margin:0;padding:0}
form.comment p{margin:0;padding:0;text-indent:100px;}
form.comment p.submit{text-align:right;}
form.comment .author img{height:25px;width:25px;border:1px solid #aaa;margin:1px;padding:1px;float:left;}
form.comment div.text{width:600px;float:left;margin:0 0 0 10px;padding:0;}
input{width:auto;}
p.submit input{margin:8px;}
</style>
<link rel="stylesheet" href="/static/js/kindeditor/themes/default/default.css">
<script type="text/javascript" src="/static/js/kindeditor/kindeditor.js"></script>
<script type="text/javascript" src="/static/js/kindeditor/lang/zh_CN.js"></script>
<script>
        var editor;
        KindEditor.ready(function(K) {
                editor = K.create('#id_comment', {
                        resizeType : 2,
                        allowImageUpload:true,
                        height:'200px',
                        width:'650px',
                        fontSizeTable:'14px',
                        filterMode :true,
                        items:['undo','redo','copy','paste','|', 'justifyleft', 'justifycenter', 'justifyright','justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent'],
                        htmlTags:{
                             span : ['style'],
                             div : ['class', 'align', 'style'],
                             a : ['class', 'href', 'target', 'name', 'style'],
                             br : ['/'],
                             'p,ol,ul,li,blockquote,h1,h2,h3,h4,h5,h6' : ['align', 'style'],
                             'tbody,tr,strong,b,sub,sup,em,i,u,strike' : []
                        },
                        




                });



                 $('input#comment_submit').click( function() {
                    var v  = editor.html();
                    if(v == ''){
                        return false;
                    }
                    
                });
        });


</script>
    {% if request.user.is_authenticated %}
    {% load comments %}
    <form class="comment" action="{% comment_form_target %}" method="POST" id="comment_form">{% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% for field in form %}
            {% if field.is_hidden %}{{ field }}{% endif %}
        {% endfor %}
            {% if request.user.is_anonymous %}
                <p><label>称呼</label>{{ form.name }}</p>
                <p><label>Email</label>{{ form.email }}</p>
                <p><label>站点</label>{{ form.url }}</p>
                <p>{{ form.comment }}</p>
            {% else %}
              <!--   <div class="author">
                    <a href="/home/{{ request.user.id }}/">
                        <img src="{{ request.user.username }}"
                             alt="{{ request.user.get_profile.screen_name }}">
                    </a>
                </div> -->
                <div class="text">{{ form.comment }}</div>
                <div class="clear"></div>
            {% endif %}
            <p class="submit"><input class="button" type="submit" value="写上去！" style="width:80px;" id="comment_submit"></p>
    </form>
    {% else %}
        <div class="please-login">你尚未登录，请先<a href="/accounts/login/">登录</a>/<a href="/accounts/register/">注册</a>
            后发表回复。</div>
    {% endif %}

deliverkindle/templates/comments/list.html
<div id='response'>
<h3>网友的回应({{ comment_count }})</h3>
{% for comment in comment_list %}
    <div class="item">
        <div class="meta">
           <!--  <div class="avatar">
                {% if comment.user_id %}
                    <a href="/home/{{ comment.user_id }}/">
                {% else %}
                    <a href="{{ comment.user_url }}" title="{{ comment.user_url }}" target="_blank">
                {% endif %}
                    <img src="{{ comment.user.username }}">
                </a>
            </div> -->
            &nbsp; 来自：
                {% if comment.user_id %}
                    <a href="/home/{{ comment.user_id }}/">
                {% else %}
                    <a href="{{ comment.user_url }}" title="{{ comment.user_url }}" target="_blank">
                {% endif %}
            {{ comment.user.get_profile.screen_name|default:comment.user_name }}</a>
            @ {{ comment.submit_date }}
            <div class="content">{% autoescape off %}{{ comment.comment|cut:"&nbsp;" }}{% endautoescape %}</div>
        </div>
        <div class="clear"></div>
    </div><!-- end item -->
{% endfor %}
</div><!-- end response -->

deliverkindle/templates/comments/posted.html
{% extends "comments/base.html" %}
{% block title %}发表回应{% endblock %}
{% block content%}
  <h1>^_^  你的回应在路上，稍候即达~~~</h1>
  <a href="javascript:history.go(-1);locate.reload();">点我返回</a>
{% endblock %}